# Generated by Django 5.2.7 on 2026-09-28 23:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="nombre"),
                ),
                ("slug", models.SlugField(max_length=90, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="correo"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("blog", "Boletín del blog"),
                            ("capital_check", "Capital Check AI"),
                        ],
                        default="blog",
                        max_length=20,
                        verbose_name="origen",
                    ),
                ),
                (
                    "diagnosis",
                    models.JSONField(blank=True, null=True, verbose_name="diagnóstico"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "suscriptor",
                "verbose_name_plural": "suscriptores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="nombre"),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
            ],
            options={
                "verbose_name": "etiqueta",
                "verbose_name_plural": "etiquetas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                (
                    "slug",
                    models.SlugField(max_length=220, unique_for_date="published_at"),
                ),
                (
                    "pillar",
                    models.CharField(
                        choices=[
                            ("numeros", "Números"),
                            ("datos", "Datos"),
                            ("narrativa", "Narrativa"),
                            ("capital", "Capital"),
                        ],
                        default="numeros",
                        max_length=12,
                        verbose_name="pilar",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Aparece en listados y en la vista previa al compartir.",
                        max_length=300,
                        verbose_name="resumen",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Separa los párrafos con una línea en blanco.",
                        verbose_name="contenido",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Borrador"), ("published", "Publicado")],
                        default="draft",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="destacado"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de publicación",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="blog.category",
                        verbose_name="categoría",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts",
                        to="blog.tag",
                        verbose_name="etiquetas",
                    ),
                ),
            ],
            options={
                "verbose_name": "artículo",
                "verbose_name_plural": "artículos",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nombre")),
                ("email", models.EmailField(max_length=254, verbose_name="correo")),
                ("body", models.TextField(max_length=2000, verbose_name="comentario")),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="aprobado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                        verbose_name="artículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "comentario",
                "verbose_name_plural": "comentarios",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-published_at"], name="blog_post_publish_2c9212_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status"], name="blog_post_status_02ce19_idx"),
        ),
    ]
