# Generated by Django 5.2.7 on 2026-10-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvaluacionFinanciera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_emprendimiento",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del emprendimiento"
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            (
                                "Sesión 1: Diagnóstico Inicial",
                                "Sesión 1: Diagnóstico Inicial",
                            ),
                            (
                                "Sesión 4: Evaluación Final",
                                "Sesión 4: Evaluación Final",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Etapa de evaluación",
                    ),
                ),
                (
                    "nivel_flujo_caja",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Nivel de conocimiento en flujo de caja (1-5)",
                    ),
                ),
                (
                    "nivel_fuentes_financiacion",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Nivel de conocimiento en fuentes de financiación (1-5)",
                    ),
                ),
                (
                    "ventas_mensuales",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Ventas mensuales"
                    ),
                ),
                (
                    "costos_variables_totales",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Costos variables totales",
                    ),
                ),
                (
                    "costos_fijos_mensuales",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Costos fijos mensuales",
                    ),
                ),
                (
                    "plan_accion_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="planes_accion/",
                        verbose_name="Plan de acción financiero a 12 meses",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
